### ISSUE TITLE
Using Transparent Bg on Viewport distorts colors

### ISSUE THREAD

**Issue by SereneMango** [griffinjennings/GodotDitheringShader#1]
It occurs whenever I have added DirectionalLight and/or WorldEnvironment in the scene.

**Comment by griffinjennings** [comment]
I forgot to add the alpha channel of the viewport back in to the final texture. Added a commit that should hopefully fix the issue

**Comment by SereneMango** [comment]
Upon further experimentation, it (still) occurs when I'm using GLES3.

**Comment by griffinjennings** [comment]
Wow, you're right, that was weird. It seems like enabling transparent_bg changes the way values are passed to the shader - when it's enabled, if the given value of any RGB channel is 1 or higher, my shader code resets it back to 0 for some reason.

I've pushed a fix now which should take care of the issue, let me know if it works
